version: "3.8"

services:
  redis:
    image: redis
    # 不暴露任何端口，只在docker内部使用
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - internal_net

  favicondb:
    image: docker.io/firshme/favicondb:x86
    container_name: favicondb
    shm_size: "1g"
    ports:
      - "8000:8000"
    networks:
      - internal_net
    depends_on:
      - redis
    restart: always

networks:
  internal_net:
    driver: bridge